[project]
name = "mongodb"
version = "0.1.0"
description = "Real Python MongoDB tutorial"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pymongo>=4.15.3",
]

[dependency-groups]
dev = [
    "ruff>=0.14.4",
]
